baseURL: https://chapter-13-09.hugoinaction.com
languageCode: en-us
title: Acme Corporation
enableEmoji: true
enableGitInfo: true
pagination:
  pagerSize: 3
theme: github.com/hugoinaction/AcmeTheme
enableRobotsTXT: true