baseURL: https://chapter-13-06.hugoinaction.com
languageCode: en-us
title: Acme Corporation
enableEmoji: true
enableGitInfo: true
Paginate: 3
theme: github.com/hugoinaction/AcmeTheme
enableRobotsTXT: true