baseURL = "http://example.org/"
languageCode = "en-us"
title = "Acme Corporation"
theme = "Universal"
enableEmoji = true

[author]
facebook = "https://facebook.com/example"
twitter = "https://twitter.com/example"
email = "contact@example.org"
name = "Acme Corporation"
location = "New York"
phone = "(999) 999-9999"
hours = "**Mon-Fri:** 9:00AM - 6:00PM, ET"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 100

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 200

[params]
color = "#4f46e5"
copyright = "Copyright &copy; 2022 Acme Corporation. All Rights Reserved."
style = "blue"
logo = "/image/logo.png"
logo_small = "/image/logo.png"
about_us = """
Acme Corporation is the world's leading manufacturer  of digital shapes. From squares and circles to  triangles and hexagons, we have it all. Browse through  our collection of various forms with different  thicknesses and line styles. We shape the world. You live in it.
"""

  [[params.footer]]
  title = "About"
  content = """
Acme Corporation is the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thicknesses and line styles. We shape the world. You live in it.
"""

  [[params.footer]]
  title = "Recent Blog Posts"
  recents = "blog"
  recentCount = 7

  [[params.footer]]
  title = "Contact Us"
  contact = true

  [params.recent_posts]
  enable = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
lineNos = true
