[module.hugoVersion]
min = "0.91.2"

[[module.imports]]
path = "github.com/hugoinaction/AcmeSupport"

  [[module.imports.mounts]]
  source = "assets"
  target = "assets"

[[module.imports]]
path = "github.com/hugoinaction/hugo-debug-utils"
